/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    ColorSwitchComponent: typeof import('./src/components/ColorSwitchComponent.vue')['default']
    Fieldset: typeof import('primevue/fieldset')['default']
    IconsComponent: typeof import('./src/components/IconsComponent.vue')['default']
    LogoComponent: typeof import('./src/components/LogoComponent.vue')['default']
    Menubar: typeof import('primevue/menubar')['default']
    NavComponent: typeof import('./src/components/NavComponent.vue')['default']
    RadioButton: typeof import('primevue/radiobutton')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SwitcherComponent: typeof import('./src/components/SwitcherComponent.vue')['default']
    TheHeader: typeof import('./src/components/blocks/TheHeader.vue')['default']
  }
}
