/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Advantages: typeof import('./src/components/blocks/Advantages.vue')['default']
    AdvantagesCard: typeof import('./src/components/AdvantagesCard.vue')['default']
    AdvantagesItem: typeof import('./src/components/AdvantagesItem.vue')['default']
    AdvantagesItemComponent: typeof import('./src/components/AdvantagesItemComponent.vue')['default']
    Button: typeof import('primevue/button')['default']
    ColorSwitchComponent: typeof import('./src/components/ColorSwitchComponent.vue')['default']
    CTA: typeof import('./src/components/blocks/CTA.vue')['default']
    CTACard: typeof import('./src/components/blocks/CTACard.vue')['default']
    Fieldset: typeof import('primevue/fieldset')['default']
    FloatLabel: typeof import('primevue/floatlabel')['default']
    IconField: typeof import('primevue/iconfield')['default']
    IconsComponent: typeof import('./src/components/IconsComponent.vue')['default']
    InputGroup: typeof import('primevue/inputgroup')['default']
    InputIcon: typeof import('primevue/inputicon')['default']
    InputText: typeof import('primevue/inputtext')['default']
    LogoComponent: typeof import('./src/components/LogoComponent.vue')['default']
    Menubar: typeof import('primevue/menubar')['default']
    NavComponent: typeof import('./src/components/NavComponent.vue')['default']
    Password: typeof import('primevue/password')['default']
    PictureComponent: typeof import('./src/components/PictureComponent.vue')['default']
    PreloaderComponent: typeof import('./src/components/PreloaderComponent.vue')['default']
    RadioButton: typeof import('primevue/radiobutton')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SignOutBtn: typeof import('./src/components/SignOutBtn.vue')['default']
    SvgComponent: typeof import('./src/components/SvgComponent.vue')['default']
    SwitcherComponent: typeof import('./src/components/SwitcherComponent.vue')['default']
    TextWithCard: typeof import('./src/components/blocks/TextWithCard.vue')['default']
    TheHeader: typeof import('./src/components/blocks/TheHeader.vue')['default']
    ThemeSwitcherComponent: typeof import('./src/components/ThemeSwitcherComponent.vue')['default']
  }
}
